package com.omnillm.engines.mlcllm.runtime

import kotlin.coroutines.Continuation
import kotlin.coroutines.intrinsics.COROUTINE_SUSPENDED
import kotlin.coroutines.resumeWithException
import kotlin.coroutines.suspendCoroutine
import kotlinx.coroutines.channels.ReceiveChannel
import kotlinx.coroutines.runBlocking
import java.lang.reflect.InvocationTargetException
import java.lang.reflect.Method

/**
 * Runtime binding to the official MLC-LLM Android runtime (`mlc4j`, package
 * `ai.mlc.mlcllm`), generated per-app by upstream `mlc_llm package`
 * (mlc-ai/mlc-llm, pinned commit [MLC_LLM_PIN_COMMIT]; API shape verified against
 * `android/mlc4j/src/main/java/ai/mlc/mlcllm/` at that commit).
 *
 * Distribution reality (verified 2026-08-09): MLC-LLM does **not** publish a
 * Maven Central artifact or GitHub-release `.aar`. The Android runtime ships as a
 * generated Gradle subproject (`dist/lib/mlc4j` with `libtvm4j_runtime_packed.so`,
 * `tvm4j_core.jar` and the Kotlin `ai.mlc.mlcllm.*` API) produced by the Python
 * `mlc_llm package` toolchain (TVM compile). The app must include that generated
 * module; this bridge then binds it through its stable Kotlin API surface.
 *
 * Binding strategy: reflection against the exact upstream FQCNs + member
 * signatures (no compile-time dependency on the generated artifact), with a
 * strict load-time verification pass. On any mismatch the binding fails closed
 * ([tryLoadRuntime] false) — production must not substitute a stub.
 *
 * JNI note: the JNI layer lives inside the generated mlc4j module
 * (`JSONFFIEngine` ↔ `libtvm4j_runtime_packed.so` via `org.apache.tvm.*`); this
 * bridge does not duplicate it and never loads arbitrary `.so` paths.
 *
 * This type is Android-free and host-testable; tests bind it against a faithful
 * test double of the pinned API (see `src/test/kotlin/ai/mlc/mlcllm/`).
 */
object MlcRuntimeBridge {

    /** mlc-ai/mlc-llm commit pinned by UPSTREAM.lock (API authority for this binding). */
    const val MLC_LLM_PIN_COMMIT: String = "2f78caa4db0f90730a11ee3bb5cbd5f23bf67f9f"

    /** mlc-ai/relax (3rdparty/tvm) commit pinned by UPSTREAM.lock at that mlc-llm commit. */
    const val TVM_PIN_COMMIT: String = "837cb9de1127b48ce48e4cefe09e83215b9d4ba7"

    /** Official runtime package name generated by `mlc_llm package`. */
    const val RUNTIME_PACKAGE: String = "ai.mlc.mlcllm"

    /** Default device of the stock generated mlc4j runtime (JSONFFIEngine → `Device.opencl()`). */
    const val STOCK_DEVICE: String = "opencl"

    // Upstream FQCNs (android/mlc4j/src/main/java/ai/mlc/mlcllm at the pin).
    // `internal` so the bound [MlcEngineRef] (same file) can reuse them.
    internal const val CLASS_MLC_ENGINE: String = "$RUNTIME_PACKAGE.MLCEngine"
    internal const val CLASS_COMPLETIONS: String = "$RUNTIME_PACKAGE.Completions"
    internal const val CLASS_PROTOCOL: String = "$RUNTIME_PACKAGE.OpenAIProtocol"
    internal const val CLASS_MESSAGE: String = "$CLASS_PROTOCOL\$ChatCompletionMessage"
    internal const val CLASS_ROLE: String = "$CLASS_PROTOCOL\$ChatCompletionRole"
    internal const val CLASS_MESSAGE_CONTENT: String = "$CLASS_PROTOCOL\$ChatCompletionMessageContent"
    internal const val CLASS_STREAM_RESPONSE: String = "$CLASS_PROTOCOL\$ChatCompletionStreamResponse"
    internal const val CLASS_STREAM_CHOICE: String = "$CLASS_PROTOCOL\$ChatCompletionStreamResponseChoice"
    internal const val CLASS_USAGE: String = "$CLASS_PROTOCOL\$CompletionUsage"

    internal const val CREATE_FULL_PARAM_COUNT: Int = 19 // 18 args + Continuation
    @Volatile
    private var loadState: LoadState = LoadState.UNATTEMPTED
    private var diagnosticsBuilder: MutableList<String> = mutableListOf()

    private enum class LoadState { UNATTEMPTED, LOADED, FAILED }

    /**
     * Attempt to resolve and verify the official runtime API on the classpath.
     * Safe to call multiple times. True only when every required member matches.
     */
    @Synchronized
    fun tryLoadRuntime(): Boolean {
        when (loadState) {
            LoadState.LOADED -> return true
            LoadState.FAILED -> return false
            LoadState.UNATTEMPTED -> Unit
        }
        diagnosticsBuilder = mutableListOf()
        return try {
            verifyRuntimeApi()
            loadState = LoadState.LOADED
            true
        } catch (e: Throwable) {
            diagnosticsBuilder += "verification failed: ${e.message ?: e.javaClass.simpleName}"
            loadState = LoadState.FAILED
            false
        }
    }

    fun isRuntimePresent(): Boolean = loadState == LoadState.LOADED

    /** Human-readable diagnostics for the last load attempt (fail-closed reporting). */
    fun diagnostics(): List<String> = diagnosticsBuilder.toList()

    /** Test hook: reset load state (does not unload anything). */
    @Synchronized
    fun resetLoadStateForTest() {
        loadState = LoadState.UNATTEMPTED
    }

    /**
     * Create a bound engine handle, or null when the runtime is not present.
     * Production control plane must fail closed on null (no stub substitution).
     */
    fun createEngineOrNull(): MlcEngineRef? {
        if (!tryLoadRuntime()) return null
        return MlcEngineRef.create()
    }

    private fun fail(message: String): Nothing = throw IllegalStateException(message)

    private fun verifyRuntimeApi() {
        val engineCls = Class.forName(CLASS_MLC_ENGINE).also { cls ->
            require(!cls.isInterface) { "$CLASS_MLC_ENGINE must be a class" }
        }
        diagnosticsBuilder += "found $CLASS_MLC_ENGINE"

        engineCls.getConstructor().also { diagnosticsBuilder += "ctor() ok" }
        engineCls.getMethod("reload", String::class.java, String::class.java)
            .also { diagnosticsBuilder += "reload(String,String) ok" }
        engineCls.getMethod("unload").also { diagnosticsBuilder += "unload() ok" }
        engineCls.getMethod("reset").also { diagnosticsBuilder += "reset() ok" }
        engineCls.getMethod("getChat").also { diagnosticsBuilder += "getChat() ok" }

        val completionsCls = Class.forName(CLASS_COMPLETIONS)
        val createMethods = completionsCls.methods.filter { m ->
            m.name == "create" && m.parameterCount == CREATE_FULL_PARAM_COUNT &&
                m.parameterTypes.last() == Continuation::class.java
        }
        require(createMethods.isNotEmpty()) { "Completions.create(messages,…) full overload not found" }
        diagnosticsBuilder += "Completions.create full overload ok (${createMethods.size} match)"

        val messageCls = Class.forName(CLASS_MESSAGE)
        val roleCls = Class.forName(CLASS_ROLE)
        val contentCls = Class.forName(CLASS_MESSAGE_CONTENT)
        Class.forName(CLASS_STREAM_RESPONSE)
        Class.forName(CLASS_STREAM_CHOICE)
        Class.forName(CLASS_USAGE)
        diagnosticsBuilder += "OpenAIProtocol nested types ok"

        // Convenience ctor (role, content: String, name, tool_calls, tool_call_id)
        val msgCtor = messageCls.constructors.firstOrNull { c ->
            c.parameterTypes.size == 5 &&
                c.parameterTypes[1] == String::class.java &&
                c.parameterTypes[0] == roleCls
        } ?: fail("ChatCompletionMessage convenience ctor not found")
        diagnosticsBuilder += "ChatCompletionMessage ctor(role,String) ok"

        require(Enum::class.java.isAssignableFrom(roleCls)) { "ChatCompletionRole must be an enum" }
        require(roleCls.enumConstants!!.any { (it as Enum<*>).name == "user" }) {
            "ChatCompletionRole.user missing"
        }
        diagnosticsBuilder += "ChatCompletionRole enum ok"

        require(contentCls.getMethod("asText").returnType == String::class.java) {
            "ChatCompletionMessageContent.asText() signature mismatch"
        }
        diagnosticsBuilder += "ChatCompletionMessageContent.asText() ok"

        val responseCls = Class.forName(CLASS_STREAM_RESPONSE)
        responseCls.getMethod("getId")
        responseCls.getMethod("getChoices")
        responseCls.getMethod("getUsage")
        val choiceCls = Class.forName(CLASS_STREAM_CHOICE)
        choiceCls.getMethod("getDelta")
        choiceCls.getMethod("getFinish_reason")
        val usageCls = Class.forName(CLASS_USAGE)
        usageCls.getMethod("getPrompt_tokens")
        usageCls.getMethod("getCompletion_tokens")
        diagnosticsBuilder += "stream response accessors ok"
    }

    /**
     * Invoke a Kotlin `suspend` function reflectively from a non-suspend context.
     * Handles the continuation-passing shape produced by the Kotlin compiler;
     * resumes synchronously when the callee does not suspend.
     */
    @Suppress("UNCHECKED_CAST")
    internal suspend fun <T> invokeSuspendMethod(method: Method, receiver: Any, vararg args: Any?): T =
        suspendCoroutine { cont ->
            val jvmContinuation = object : Continuation<T> {
                override val context = cont.context
                override fun resumeWith(result: Result<T>) = cont.resumeWith(result)
            }
            try {
                val ret = method.invoke(receiver, *args, jvmContinuation)
                if (ret !== COROUTINE_SUSPENDED) {
                    cont.resumeWith(Result.success(ret as T))
                }
            } catch (e: InvocationTargetException) {
                cont.resumeWithException(e.cause ?: e)
            } catch (e: Throwable) {
                cont.resumeWithException(e)
            }
        }
}

/**
 * One MLC-LLM conversation turn: role + content pair for the OpenAI-style
 * `chat.completions` message list.
 */
data class MlcMessageEntry(val role: String, val content: String)

/** Sampling parameters passed through to `Completions.create(...)`. */
data class MlcSamplingParams(
    val maxTokens: Int? = null,
    val temperature: Float? = null,
    val topP: Float? = null,
    val topK: Int? = null,
    val stopSequences: List<String>? = null,
)

/** Result of one completed chat streaming turn. */
data class MlcChatResult(
    val text: String,
    val promptTokens: Int?,
    val completionTokens: Int?,
    val finishReason: String?,
)

/**
 * Bound handle to a live `ai.mlc.mlcllm.MLCEngine` instance (reflectively).
 *
 * Never exposes raw pointers; all members are resolved at construction and
 * cached. All upstream calls are made on the calling thread (upstream `reload`
 * is synchronous; streaming is drained by [streamChat]).
 */
class MlcEngineRef private constructor(
    private val engine: Any,
    private val reloadMethod: Method,
    private val unloadMethod: Method,
    private val resetMethod: Method,
    private val createMethod: Method,
    private val messageCtor: java.lang.reflect.Constructor<*>,
    private val roleCls: Class<*>,
    private val contentCls: Class<*>,
    private val responseCls: Class<*>,
    private val choiceCls: Class<*>,
    private val usageCls: Class<*>,
) {

    /** Upstream runtime identity for diagnostics (not a trust elevation). */
    val libraryLabel: String =
        "mlc-llm-runtime(${MlcRuntimeBridge.MLC_LLM_PIN_COMMIT.take(7)}):mlc4j"

    private val completions: Any by lazy {
        val chat = engine.javaClass.getMethod("getChat").invoke(engine)
        chat.javaClass.getMethod("getCompletions").invoke(chat)
    }

    /**
     * Load a compiled model bundle. [modelPath] must be the installation
     * directory containing `mlc-chat-config.json` + weights; [modelLib] the
     * packaged compiled library name (upstream `"system://$modelLib"`).
     * Upstream `reload` is synchronous.
     */
    fun reload(modelPath: String, modelLib: String) {
        try {
            reloadMethod.invoke(engine, modelPath, modelLib)
        } catch (e: InvocationTargetException) {
            throw MlcRuntimeException(e.cause ?: e)
        } catch (e: Throwable) {
            throw MlcRuntimeException(e)
        }
    }

    fun unload() {
        try {
            unloadMethod.invoke(engine)
        } catch (_: Throwable) {
            // Best-effort release (ENGINE-MLC §4/§9); token invalidated by caller.
        }
    }

    fun reset() {
        try {
            resetMethod.invoke(engine)
        } catch (_: Throwable) {
            // Best-effort; the runtime reports errors through generate paths.
        }
    }

    /**
     * Run one streaming chat completion over [messages] (full OpenAI-style
     * history — the MLC chat API is stateless per request). Blocks until the
     * stream closes (channel close on usage). [onDelta] receives each emitted
     * delta text; return false to stop consuming early (cooperative cancel —
     * the upstream background stream is left to close naturally).
     */
    fun streamChat(
        messages: List<MlcMessageEntry>,
        params: MlcSamplingParams,
        onDelta: (String) -> Boolean,
    ): MlcChatResult = runBlocking {
        val request = buildRequest(messages, params)
        val channel = MlcRuntimeBridge.invokeSuspendMethod<Any>(
            createMethod,
            completions,
            *request,
        ) as ReceiveChannel<*>

        val text = StringBuilder()
        var promptTokens: Int? = null
        var completionTokens: Int? = null
        var stopConsuming = false

        while (true) {
            if (stopConsuming) break
            val result = channel.receiveCatching()
            if (result.isClosed) break
            val item = result.getOrNull() ?: break
            try {
                parseStreamResponse(item) { delta ->
                    if (onDelta(delta)) {
                        text.append(delta)
                    } else {
                        stopConsuming = true
                    }
                }?.let { usage ->
                    promptTokens = usage.first
                    completionTokens = usage.second
                }
            } catch (e: MlcRuntimeException) {
                // Parsing of one chunk must not kill the turn silently — surface it.
                throw e
            }
        }
        MlcChatResult(text.toString(), promptTokens, completionTokens, observedFinishReason())
    }

    private fun buildRequest(
        messages: List<MlcMessageEntry>,
        params: MlcSamplingParams,
    ): Array<Any?> {
        val roleUser = roleCls.enumConstants!!.first { (it as Enum<*>).name == "user" }
        val roleAssistant = roleCls.enumConstants!!.first { (it as Enum<*>).name == "assistant" }
        val built = messages.map { entry ->
            val role = when (entry.role) {
                "assistant" -> roleAssistant
                else -> roleUser
            }
            messageCtor.newInstance(role, entry.content, null, null, null)
        }
        val stopList = params.stopSequences?.let { java.util.ArrayList<String>(it) }
        return arrayOf(
            java.util.ArrayList<Any>(built), // messages
            null,                            // model
            null,                            // frequency_penalty
            null,                            // presence_penalty
            false,                           // logprobs
            0,                               // top_logprobs
            null,                            // logit_bias
            params.maxTokens,                // max_tokens
            1,                               // n
            null,                            // seed
            stopList,                        // stop
            true,                            // stream
            null,                            // stream_options
            params.temperature,              // temperature
            params.topP,                     // top_p
            null,                            // tools
            null,                            // user
            null,                            // response_format
        )
    }

    /**
     * Extract delta text + optional usage from one streamed response chunk.
     * Returns (promptTokens, completionTokens) when the chunk carries usage.
     */
    private fun parseStreamResponse(
        item: Any,
        onDelta: (String) -> Unit,
    ): Pair<Int, Int>? {
        if (!responseCls.isInstance(item)) {
            throw MlcRuntimeException(
                IllegalStateException("unexpected stream item type: ${item.javaClass.name}"),
            )
        }
        val choices = item.javaClass.getMethod("getChoices").invoke(item) as List<*>
        for (rawChoice in choices) {
            if (rawChoice == null || !choiceCls.isInstance(rawChoice)) continue
            val choice: Any = rawChoice
            choice.javaClass.getMethod("getFinish_reason").invoke(choice)?.let {
                finishReasonCache = it as? String ?: finishReasonCache
            }
            val rawDelta = choice.javaClass.getMethod("getDelta").invoke(choice) ?: continue
            val rawContent = rawDelta.javaClass.getMethod("getContent").invoke(rawDelta) ?: continue
            if (!contentCls.isInstance(rawContent)) continue
            val text = rawContent.javaClass.getMethod("asText").invoke(rawContent) as? String
            if (!text.isNullOrEmpty()) onDelta(text)
        }
        val usage = item.javaClass.getMethod("getUsage").invoke(item)
        return if (usage != null && usageCls.isInstance(usage)) {
            val prompt = usage.javaClass.getMethod("getPrompt_tokens").invoke(usage) as Int
            val completion = usage.javaClass.getMethod("getCompletion_tokens").invoke(usage) as Int
            Pair(prompt, completion)
        } else {
            null
        }
    }

    /** Finish reason observed on the last chunk (adapter drains before terminal). */
    private var finishReasonCache: String? = null

    /** Expose observed finish reason (upstream sets it on the final delta chunk). */
    internal fun observedFinishReason(): String? = finishReasonCache

    companion object {
        fun create(): MlcEngineRef {
            val engineCls = Class.forName(MlcRuntimeBridge.CLASS_MLC_ENGINE)
            val engine = engineCls.getConstructor().newInstance()
            val chat = engineCls.getMethod("getChat").invoke(engine)
            val completions = chat.javaClass.getMethod("getCompletions").invoke(chat)
            val createMethod = completions.javaClass.methods.first { m ->
                m.name == "create" && m.parameterCount ==
                    MlcRuntimeBridge.CREATE_FULL_PARAM_COUNT &&
                    m.parameterTypes.last() == Continuation::class.java
            }
            return MlcEngineRef(
                engine = engine,
                reloadMethod = engineCls.getMethod("reload", String::class.java, String::class.java),
                unloadMethod = engineCls.getMethod("unload"),
                resetMethod = engineCls.getMethod("reset"),
                createMethod = createMethod,
                messageCtor = Class.forName(MlcRuntimeBridge.CLASS_MESSAGE).constructors
                    .first { c ->
                        c.parameterTypes.size == 5 && c.parameterTypes[1] == String::class.java
                    },
                roleCls = Class.forName(MlcRuntimeBridge.CLASS_ROLE),
                contentCls = Class.forName(MlcRuntimeBridge.CLASS_MESSAGE_CONTENT),
                responseCls = Class.forName(MlcRuntimeBridge.CLASS_STREAM_RESPONSE),
                choiceCls = Class.forName(MlcRuntimeBridge.CLASS_STREAM_CHOICE),
                usageCls = Class.forName(MlcRuntimeBridge.CLASS_USAGE),
            )
        }
    }
}

/** Wraps an upstream runtime error with its original cause (message only — no pointers). */
class MlcRuntimeException(cause: Throwable) : RuntimeException(cause.message ?: cause.javaClass.simpleName, cause)
