package com.omnillm.companion

import java.io.ByteArrayOutputStream
import java.security.MessageDigest
import java.security.SecureRandom
import javax.crypto.Mac
import javax.crypto.spec.SecretKeySpec

/**
 * Host-issued work ticket for companion (SEC-EXTERNAL-SANDBOX §3).
 *
 * Main app builds this; companion validates and reports package signer digest,
 * version, process instance, and supported protocol. Any mismatch fails closed.
 * Replay, stale runtime epoch, or different artifact IDs are rejected.
 *
 * SEC-07: [macHex] authenticates the ticket — HMAC-SHA-256 over the canonical
 * field encoding with the per-instance pairing key established at
 * [CompanionSandboxService.attachSupervisor] time (generated by the companion,
 * delivered to the host in the attach result attributes, never stored). The
 * companion verifies the MAC before any field checks; forged / missing /
 * wrong-key tickets fail closed with `INVALID_AUTH`.
 *
 * Pure data — no Android types (unit-testable without instrumentation).
 */
data class SandboxExecutionTicket(
    val protocolMajor: Int,
    val protocolMinor: Int,
    /** Runtime instance identity (opaque, non-secret). */
    val runtimeInstanceId: String,
    val runtimeEpoch: Long,
    val bootId: String,
    /** Operation / durable commit id (claim ledger). */
    val operationId: String,
    val commitId: String,
    val engineBuildId: String,
    /** Model content digests / revision pins (hex or catalog ids — not paths). */
    val modelContentIds: List<String>,
    val backend: String,
    /** Opaque resource envelope summary (dimensions only; not a charge authority). */
    val resourceEnvelopeSummary: String,
    val operatingConstraintSummary: String,
    val monotonicDeadlineMs: Long,
    /** One-shot nonce; replay rejected. */
    val nonce: String,
    /** Placement class must be EXTERNAL_UID_ACCELERATED for this path. */
    val placementClass: String,
    /**
     * HMAC-SHA-256 over the canonical authenticated fields (SEC-07),
     * lowercase hex, key = per-instance pairing key from attach.
     * Format is intentionally NOT enforced at construction — malformed or empty
     * values are rejected by [CompanionTicketValidator] with `INVALID_AUTH`.
     */
    val macHex: String,
) {
    init {
        require(protocolMajor > 0) { "protocolMajor must be positive" }
        require(protocolMinor >= 0) { "protocolMinor must be non-negative" }
        require(runtimeInstanceId.isNotEmpty()) { "runtimeInstanceId must be non-empty" }
        require(runtimeEpoch >= 0L) { "runtimeEpoch must be non-negative" }
        require(bootId.isNotEmpty()) { "bootId must be non-empty" }
        require(operationId.isNotEmpty()) { "operationId must be non-empty" }
        require(commitId.isNotEmpty()) { "commitId must be non-empty" }
        require(engineBuildId.isNotEmpty()) { "engineBuildId must be non-empty" }
        require(modelContentIds.isNotEmpty() && modelContentIds.all { it.isNotEmpty() }) {
            "modelContentIds required"
        }
        require(backend.isNotEmpty()) { "backend must be non-empty" }
        require(nonce.isNotEmpty()) { "nonce must be non-empty" }
        require(placementClass.isNotEmpty()) { "placementClass must be non-empty" }
        require(monotonicDeadlineMs >= 0L) { "monotonicDeadlineMs must be non-negative" }
    }
}

/**
 * HMAC-SHA-256 ticket authenticator (SEC-07).
 *
 * Key: 256-bit per-instance pairing key. The companion generates it during
 * [CompanionSandboxService.attachSupervisor] (pairing) and returns it to the
 * host in the attach result attributes (`sessionMacKeyHex`) over the
 * signature-gated Binder channel. The host must MAC every ticket with that key
 * from then on; the companion verifies with constant-time comparison
 * ([MessageDigest.isEqual]) so ticket forgery without the key fails closed.
 *
 * Canonical encoding is unambiguous (length-prefixed UTF-8, declaration order)
 * so field boundaries cannot be confused with embedded separators.
 */
object SandboxTicketMac {

    const val ALGORITHM: String = "HmacSHA256"
    const val KEY_BYTES: Int = 32
    const val MAC_HEX_LENGTH: Int = 64

    private val secureRandom: SecureRandom = SecureRandom()

    /** Fresh 256-bit per-instance pairing key (SEC-07). */
    fun randomKeyBytes(): ByteArray {
        val out = ByteArray(KEY_BYTES)
        secureRandom.nextBytes(out)
        return out
    }

    /** HMAC-SHA-256 over the canonical authenticated fields, lowercase hex. */
    fun computeHex(key: ByteArray, ticket: SandboxExecutionTicket): String =
        encodeHex(hmac(key, canonicalBytes(ticket)))

    /** Constant-time verification; malformed / missing / wrong-key MACs fail. */
    fun verify(key: ByteArray, ticket: SandboxExecutionTicket): Boolean {
        val expected = hmac(key, canonicalBytes(ticket))
        val presented = decodeHex(ticket.macHex) ?: return false
        return MessageDigest.isEqual(expected, presented)
    }

    fun isValidMacHex(value: String): Boolean =
        value.length == MAC_HEX_LENGTH && value.all { it.isDigit() || it in 'a'..'f' }

    fun encodeHex(bytes: ByteArray): String {
        val sb = StringBuilder(bytes.size * 2)
        for (b in bytes) {
            sb.append(HEX[(b.toInt() ushr 4) and 0x0f])
            sb.append(HEX[b.toInt() and 0x0f])
        }
        return sb.toString()
    }

    /**
     * Canonical unambiguous encoding of every authenticated field (macHex
     * excluded): each field is 4-byte big-endian length-prefixed UTF-8 in
     * declaration order; the model id list is count + element prefixes.
     */
    fun canonicalBytes(ticket: SandboxExecutionTicket): ByteArray {
        val out = ByteArrayOutputStream()
        writeStringField(out, ticket.protocolMajor.toString())
        writeStringField(out, ticket.protocolMinor.toString())
        writeStringField(out, ticket.runtimeInstanceId)
        writeStringField(out, ticket.runtimeEpoch.toString())
        writeStringField(out, ticket.bootId)
        writeStringField(out, ticket.operationId)
        writeStringField(out, ticket.commitId)
        writeStringField(out, ticket.engineBuildId)
        writeInt32(out, ticket.modelContentIds.size)
        for (id in ticket.modelContentIds) writeStringField(out, id)
        writeStringField(out, ticket.backend)
        writeStringField(out, ticket.resourceEnvelopeSummary)
        writeStringField(out, ticket.operatingConstraintSummary)
        writeStringField(out, ticket.monotonicDeadlineMs.toString())
        writeStringField(out, ticket.nonce)
        writeStringField(out, ticket.placementClass)
        return out.toByteArray()
    }

    private fun hmac(key: ByteArray, message: ByteArray): ByteArray {
        require(key.size == KEY_BYTES) { "ticket MAC key must be 256-bit" }
        val mac = Mac.getInstance(ALGORITHM)
        mac.init(SecretKeySpec(key, ALGORITHM))
        return mac.doFinal(message)
    }

    private fun writeStringField(out: ByteArrayOutputStream, value: String) {
        val bytes = value.toByteArray(Charsets.UTF_8)
        writeInt32(out, bytes.size)
        out.write(bytes, 0, bytes.size)
    }

    private fun writeInt32(out: ByteArrayOutputStream, value: Int) {
        out.write(value ushr 24 and 0xff)
        out.write(value ushr 16 and 0xff)
        out.write(value ushr 8 and 0xff)
        out.write(value and 0xff)
    }

    private fun decodeHex(hex: String): ByteArray? {
        if (hex.length % 2 != 0 || !isValidMacHex(hex)) return null
        val out = ByteArray(hex.length / 2)
        for (i in out.indices) {
            val hi = Character.digit(hex[i * 2], 16)
            val lo = Character.digit(hex[i * 2 + 1], 16)
            if (hi < 0 || lo < 0) return null
            out[i] = ((hi shl 4) or lo).toByte()
        }
        return out
    }

    private val HEX = "0123456789abcdef".toCharArray()
}

/**
 * Companion identity report returned after successful handshake (SEC-EXTERNAL-SANDBOX §3).
 */
data class CompanionIdentityReport(
    val packageName: String,
    val packageVersionName: String,
    val packageVersionCode: Long,
    /** Signer cert digest (hex) — host compares to expected same-signer set. */
    val signerDigestHex: String,
    val processInstanceId: String,
    val pid: Int,
    val protocolMajor: Int,
    val protocolMinor: Int,
    val uid: Int,
) {
    init {
        require(packageName.isNotEmpty())
        require(processInstanceId.isNotEmpty())
        require(signerDigestHex.isNotEmpty())
        require(protocolMajor > 0)
        require(pid > 0)
    }
}

sealed class TicketValidationResult {
    data class Accepted(val reportHints: Map<String, String> = emptyMap()) : TicketValidationResult()

    data class Rejected(
        /** Catalog error code when applicable (e.g. TRUST_PLACEMENT_REQUIRED, INVALID_REQUEST). */
        val errorCode: String,
        val message: String,
    ) : TicketValidationResult()
}

/**
 * Pure ticket validation (SEC-EXTERNAL-SANDBOX §3, §7, SEC-07).
 * No I/O; host still performs signer/package probes separately.
 *
 * SEC-07: MAC verification is the FIRST check — every ticket must carry a valid
 * HMAC-SHA-256 computed with the per-instance pairing key ([SandboxTicketMac]).
 * Only after authentication pass are protocol/context/placement/replay/deadline
 * constraints evaluated.
 */
object CompanionTicketValidator {

    const val PLACEMENT_EXTERNAL_UID_ACCELERATED: String = "EXTERNAL_UID_ACCELERATED"

    fun validate(
        ticket: SandboxExecutionTicket,
        macKey: ByteArray,
        expectedRuntimeEpoch: Long,
        expectedBootId: String,
        expectedRuntimeInstanceId: String,
        claimedNonces: Set<String>,
        supportedProtocolMajor: Int = CompanionSandboxModule.PROTOCOL_MAJOR,
        supportedProtocolMinor: Int = CompanionSandboxModule.PROTOCOL_MINOR,
        nowMonotonicMs: Long,
    ): TicketValidationResult {
        if (!SandboxTicketMac.verify(macKey, ticket)) {
            return TicketValidationResult.Rejected(
                errorCode = "INVALID_AUTH",
                message = "ticket MAC invalid or missing (authenticated tickets only)",
            )
        }
        if (ticket.protocolMajor != supportedProtocolMajor) {
            return TicketValidationResult.Rejected(
                errorCode = "INVALID_REQUEST",
                message = "protocol major mismatch",
            )
        }
        if (ticket.protocolMinor > supportedProtocolMinor) {
            return TicketValidationResult.Rejected(
                errorCode = "INVALID_REQUEST",
                message = "protocol minor not supported",
            )
        }
        if (ticket.runtimeInstanceId != expectedRuntimeInstanceId) {
            return TicketValidationResult.Rejected(
                errorCode = "INVALID_REQUEST",
                message = "runtime instance mismatch",
            )
        }
        if (ticket.bootId != expectedBootId) {
            return TicketValidationResult.Rejected(
                errorCode = "INVALID_REQUEST",
                message = "bootId mismatch",
            )
        }
        if (ticket.runtimeEpoch != expectedRuntimeEpoch) {
            return TicketValidationResult.Rejected(
                errorCode = "INVALID_REQUEST",
                message = "runtime epoch mismatch or replay",
            )
        }
        if (ticket.placementClass != PLACEMENT_EXTERNAL_UID_ACCELERATED) {
            return TicketValidationResult.Rejected(
                errorCode = "TRUST_PLACEMENT_REQUIRED",
                message = "companion only accepts EXTERNAL_UID_ACCELERATED",
            )
        }
        if (ticket.nonce in claimedNonces) {
            return TicketValidationResult.Rejected(
                errorCode = "IDEMPOTENCY_CONFLICT",
                message = "ticket nonce already claimed; query host ledger",
            )
        }
        if (nowMonotonicMs > ticket.monotonicDeadlineMs) {
            return TicketValidationResult.Rejected(
                errorCode = "INVALID_REQUEST",
                message = "ticket deadline exceeded",
            )
        }
        return TicketValidationResult.Accepted()
    }
}
