package com.omnillm.interfaces.aidl

import com.omnillm.interfaces.AidlModule

/**
 * Binder projection authority (CORE-INTERFACE / ANDROID binder boundaries).
 *
 * `.aidl` files under `src/main/aidl` are **projections** of
 * `specs/aidl/omnillm-aidl.yaml`. Regenerated by `tools/codegen/extract_aidl.py`.
 * Do not invent interfaces, parcelable fields, or protocol versions in Kotlin.
 */
object AidlAuthority {
    const val SPEC_REPO_PATH: String = AidlModule.AIDL_SPEC_PATH
    const val PACKAGE: String = AidlModule.AIDL_PACKAGE
    const val SCHEMA_VERSION: Int = 2
    const val BINDER_TRANSACTION_BUDGET_BYTES: Int = 524_288

    /**
     * Declaration inventory from omnillm-aidl.yaml (scaffold lock).
     * Interfaces + parcelables; keep aligned with extract_aidl output.
     */
    val DECLARATION_NAMES: Set<String> = setOf(
        "CommandResult",
        "OmniCommandRequest",
        "IJobObserver",
        "IOmniAdmin",
        "IOmniBinding",
        "IOmniRuntime",
        "IOmniStreamCallback",
        "IStreamSession",
        "OmniAdminSnapshot",
        "OmniAssetCreateRequest",
        "OmniAssetInfo",
        "OmniAssetUploadRequest",
        "OmniBenchmarkJobParameters",
        "OmniCapabilityEntry",
        "OmniChatMessage",
        "OmniChatRequest",
        "OmniContentReportInfo",
        "OmniContentReportJobParameters",
        "OmniContentReportProposalRequest",
        "OmniConsentGrant",
        "OmniContentReportReceipt",
        "OmniDeleteJobParameters",
        "OmniDiagnosticExportJobParameters",
        "OmniDownloadJobParameters",
        "OmniEmbeddingRequest",
        "OmniError",
        "OmniErrorDetail",
        "OmniEvent",
        "OmniEventBatch",
        "OmniFallback",
        "OmniImportJobParameters",
        "OmniJobEvent",
        "OmniJobEventBatch",
        "OmniJobInfo",
        "OmniJobSpec",
        "OmniModelInfo",
        "OmniModelPage",
        "OmniPairingChallenge",
        "OmniPairingRequest",
        "OmniPairingStatus",
        "OmniRequestState",
        "OmniSettingEntry",
        "OmniSettingsPatch",
        "OmniSettingsSnapshot",
    )

    val RUNTIME_INTERFACES: Set<String> = setOf(
        "IOmniBinding",
        "IOmniRuntime",
        "IOmniAdmin",
        "IStreamSession",
        "IOmniStreamCallback",
        "IJobObserver",
    )
}
